#import <UIKit/UIKit.h>

NS_ASSUME_NONNULL_BEGIN

FOUNDATION_EXPORT NSData * _Nullable YTKACEMediaArtworkData(NSURL *URL);
FOUNDATION_EXPORT UIImage * _Nullable YTKACEMediaArtworkImage(NSURL *URL);

NS_ASSUME_NONNULL_END
